public class Address {
    public void homeAddress() {
        string yourName='Fatma';
        integer totalNumberOfMembers=7;
        string houseName='Vintage';
        string  houseNumber='234ad';
        string streetName='Culver';
        string cityName='Plano';
        string stateName='Utah';
        string stateISOcode='US-TX';
        string countryName='Dallas';
        integer countryISOcode=980;
        string zipCode='45670Ann';
        Boolean isThisYourCurrentHomeOrNot=true;

        System.debug('My name is '+ yourName);
        System.debug('My houshold number = '+ totalNumberOfMembers);
        System.debug('My house name is  '+ houseName);
        System.debug('My house number is '+ houseNumber);
        System.debug('My street is '+ streetName);
        System.debug('My state is ' + stateName);
        System.debug('My city is '+ cityName);
        System.debug('My ISO code is '+ stateISOcode);
        System.debug('My country is '+ countryName);
        System.debug('My country ISO code is '+ countryISOcode);
        System.debug('My zipcode is '+ zipCode);
        System.debug('Is this my current home '+ isThisYourCurrentHomeOrNot);
        
    }
    
}







